version: "3.7"
services:
    static:
        build: ./nginx
        ports:
            - "80:80"
        image: hidoya/nginx
        depends_on:
            - web

    web:
        build: .
        env_file:
            - secret.env
        expose:
            - "8001"
        image: hidoya/reddit_sentiment
        command: gunicorn reddit_sentiment.wsgi:application --bind 0.0.0.0:8001
